name: Update README with latest repos

on:
  schedule:
    - cron: "0 * * * *" # every 1 hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update README
        uses: anmol098/waka-readme-stats@master
        with:
          GH_USERNAME: abhijitpavse
          SHOW_PROJECTS: "true"
          SHOW_LINES_OF_CODE: "false"
