name: GitHub Metrics

on:
  schedule: [{cron: "0 * * * *"}] # every hour
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: abhijitpavse
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
