name: Generate Snake Animation

on:
  schedule: # execute every hour
    - cron: "0 * * * *"
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: abhijitpavse
          outputs: |
            dist/snake.svg?palette=github-light&color_snake=purple&color_dots=#ffffff,#00ff00,#00cc00,#009900

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
